#!/bin/bash

export LC_ALL=C

quit() {
   echo ${1}
   exit 1
}

if [[ "$(whoami)" != "root" ]]; then
    echo "Restarting as root..."
    sudo ${0} ${@}
    exit ${?}
fi

pkgs=${@}
aurs=$(pamac list -qm)

for pkg in ${pkgs}; do
    for aur in ${aurs}; do
        if [[ "${aur}" == "${pkg}" ]]; then
            continue 2
        fi
    done

    # pacman -Qkk ${pkg}
    pacman -S --noconfirm ${pkg}
done
